repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
            -   id: check-ast
            -   id: check-case-conflict
            -   id: check-json
            -   id: check-merge-conflict
            -   id: check-yaml
                args: [--unsafe]
            -   id: debug-statements
            -   id: end-of-file-fixer
            -   id: fix-encoding-pragma
            -   id: mixed-line-ending
            -   id: requirements-txt-fixer
            -   id: trailing-whitespace
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.14.13  # same as in pyproject.toml
        hooks:
            # linter
            - id: ruff-check
              args: [ --fix ]
            # formatter
            - id: ruff-format
