# -*- coding: utf-8 -*-
#
# Copyright 2022-2024 ETH Zurich
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import dataclasses
import os
import socket
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from typing import Literal

    import numpy.typing as npt


@dataclasses.dataclass
class DataTypes:
    """Specify the datatypes for bool, float and integer fields."""

    bool: npt.DTypeLike
    float: npt.DTypeLike
    int: npt.DTypeLike

    @staticmethod
    def with_precision(precision: Literal["double", "single"]) -> DataTypes:
        if precision == "double":
            return DataTypes(bool=bool, float=np.float64, int=np.int64)
        elif precision == "single":
            return DataTypes(bool=bool, float=np.float32, int=np.int32)
        else:
            raise ValueError("Either `double` or `single` precision supported.")


@dataclasses.dataclass
class GT4PyConfig:
    """Gather options controlling the compilation and execution of the code generated by GT4Py."""

    backend: str
    backend_opts: dict = dataclasses.field(default_factory=dict)
    build_info: dict | None = None
    device_sync: bool = True
    dtypes: DataTypes = dataclasses.field(default=DataTypes(bool=bool, float=float, int=int))
    exec_info: dict = dataclasses.field(default_factory=dict)
    managed: bool | str = "gt4py"
    rebuild: bool = False
    validate_args: bool = False
    verbose: bool = True

    def __post_init__(self) -> None:
        self.exec_info["__aggregate_data"] = True

    def reset_exec_info(self) -> None:
        self.exec_info = {"__aggregate_data": self.exec_info.get("__aggregate_data", True)}


@dataclasses.dataclass
class PythonConfig:
    """Gather options controlling execution of Python/GT4Py code."""

    num_cols: int

    enable_validation: bool
    input_file: str
    reference_file: str

    num_runs: int

    precision: Literal["double", "single"]
    data_types: DataTypes
    gt4py_config: GT4PyConfig
    sympl_enable_checks: bool

    atol: float | None = None
    rtol: float | None = None
    num_threads: int = -1

    def __post_init__(self) -> None:
        if self.num_threads < 1:
            self.num_threads = int(os.environ.get("OMP_NUM_THREADS", "1"))
        self.gt4py_config.dtypes = self.data_types

    def with_backend(self, backend: str | None) -> PythonConfig:
        self.gt4py_config.backend = backend
        return self

    def with_checks(self, enabled: bool) -> PythonConfig:
        self.gt4py_config.validate_args = enabled
        self.sympl_enable_checks = enabled
        return self

    def with_precision(self, precision: Literal["double", "single"]) -> PythonConfig:
        self.precision = precision
        self.data_types = self.data_types.with_precision(precision)
        return self


@dataclasses.dataclass
class FortranConfig:
    """Gather options controlling execution of FORTRAN code."""

    build_dir: str
    precision: Literal["double", "single"]
    variant: str
    nproma: int
    num_cols: int
    num_runs: int
    num_threads: int


@dataclasses.dataclass
class IOConfig:
    """Gather options for I/O."""

    output_csv_file: str | None
    host_name: str

    def __post_init__(self) -> None:
        if (f := self.output_csv_file) is not None:
            basename, extension = os.path.splitext(f)
            if not extension:
                self.output_csv_file = f + ".csv"
            elif extension != ".csv":
                self.output_csv_file = basename + ".csv"

        self.host_name = self.host_name or socket.gethostname()

    def with_host_name(self, host_name: str | None) -> IOConfig:
        args = dataclasses.asdict(self)
        args["host_name"] = host_name
        return IOConfig(**args)

    def with_output_csv_file(self, output_csv_file: str | None) -> IOConfig:
        args = dataclasses.asdict(self)
        args["output_csv_file"] = output_csv_file
        return IOConfig(**args)
